// 产品数据
export const products = [
  {
    id: 1,
    name: '企业级 SaaS 平台',
    description: '全面的企业级软件即服务解决方案，支持多租户架构',
    category: '云服务',
    features: ['多租户支持', 'API集成', '数据分析'],
    price: '定制',
    image: '/images/products/saas-platform.jpg',
    rating: 4.8,
  },
  {
    id: 2,
    name: '智能数据分析',
    description: '基于AI的数据分析和可视化平台',
    category: '数据分析',
    features: ['实时分析', '预测模型', '可视化报表'],
    price: '¥999/月',
    image: '/images/products/data-analytics.jpg',
    rating: 4.9,
  },
  {
    id: 3,
    name: '移动办公套件',
    description: '跨平台移动办公解决方案',
    category: '移动应用',
    features: ['多端同步', '离线模式', '安全加密'],
    price: '¥599/月',
    image: '/images/products/mobile-suite.jpg',
    rating: 4.7,
  },
  {
    id: 4,
    name: '客户关系管理',
    description: '智能客户关系管理系统',
    category: 'CRM',
    features: ['客户分析', '销售管道', '自动化'],
    price: '¥799/月',
    image: '/images/products/crm.jpg',
    rating: 4.6,
  },
]

// 下载数据
export const downloads = [
  {
    id: 1,
    title: 'TechCorp 桌面客户端 v3.2',
    description: '适用于 Windows 和 macOS 的桌面应用程序',
    version: '3.2.1',
    fileSize: '245 MB',
    downloads: 15234,
    updatedAt: '2024-01-15',
    category: '客户端',
    platform: ['Windows', 'macOS'],
    url: '/downloads/techcorp-desktop-3.2.1.zip',
  },
  {
    id: 2,
    title: '移动应用 iOS版',
    description: '适用于 iPhone 和 iPad 的移动应用',
    version: '2.5.0',
    fileSize: '128 MB',
    downloads: 28456,
    updatedAt: '2024-01-10',
    category: '移动应用',
    platform: ['iOS'],
    url: '/downloads/techcorp-ios-2.5.0.zip',
  },
  {
    id: 3,
    title: 'API 文档 SDK',
    description: '开发者 API 接口文档和 SDK 包',
    version: '1.8.0',
    fileSize: '45 MB',
    downloads: 8921,
    updatedAt: '2024-01-05',
    category: '开发工具',
    platform: ['跨平台'],
    url: '/downloads/api-sdk-1.8.0.zip',
  },
  {
    id: 4,
    title: '用户手册 PDF',
    description: '完整的产品使用指南和教程',
    fileSize: '18 MB',
    downloads: 35678,
    updatedAt: '2023-12-28',
    category: '文档',
    platform: ['PDF'],
    url: '/downloads/user-manual.pdf',
  },
]

// 视频数据
export const videos = [
  {
    id: 1,
    title: '产品介绍视频',
    description: '全面了解 TechCorp 平台的功能和优势',
    duration: '5:30',
    views: 15234,
    thumbnail: '/images/videos/product-intro.jpg',
    category: '产品介绍',
    url: 'https://example.com/videos/product-intro',
  },
  {
    id: 2,
    title: '快速入门教程',
    description: '10分钟快速上手使用我们的平台',
    duration: '12:15',
    views: 28456,
    thumbnail: '/images/videos/quick-start.jpg',
    category: '教程',
    url: 'https://example.com/videos/quick-start',
  },
  {
    id: 3,
    title: '客户成功案例',
    description: '了解我们的客户如何通过 TechCorp 取得成功',
    duration: '8:45',
    views: 18923,
    thumbnail: '/images/videos/case-study.jpg',
    category: '案例',
    url: 'https://example.com/videos/case-study',
  },
  {
    id: 4,
    title: '高级功能演示',
    description: '深入了解平台的高级功能和使用技巧',
    duration: '18:20',
    views: 9234,
    thumbnail: '/images/videos/advanced-features.jpg',
    category: '演示',
    url: 'https://example.com/videos/advanced-features',
  },
]

// 客服常见问题
export const faqs = [
  {
    id: 1,
    question: '如何开始免费试用？',
    answer: '点击网站右上角的"免费试用"按钮，填写基本信息即可开始30天免费试用。',
    category: '入门',
  },
  {
    id: 2,
    question: '支持哪些支付方式？',
    answer: '我们支持支付宝、微信支付、信用卡和企业转账等多种支付方式。',
    category: '支付',
  },
  {
    id: 3,
    question: '数据安全如何保障？',
    answer: '我们采用银行级别的数据加密、多地备份和严格的数据访问控制来确保您的数据安全。',
    category: '安全',
  },
  {
    id: 4,
    question: '是否支持私有化部署？',
    answer: '是的，我们提供私有化部署方案，请联系销售团队获取详细信息和报价。',
    category: '部署',
  },
]